### PR TITLE
Added support for multiple .NET versions

### PR DESCRIPTION
**Pull request by dahall**
Nice work. I like the simplicity compared to some other projects.

The changes I made are sweeping, but simple:
1. I upgraded the project and solution files to Visual Studio 2017/2019 formats.
2. I added support for .NET 2.0, 3.5, 4.0, 4.5, .NET Standard 2.0 and .NET Core 2.0 and 2.1. This was done through some minor code changes and adding the [Theraot.Core](https://github.com/theraot/Theraot) NuGet package.
3. I also ran the code through CodeMaid to provide syntax and style consistency.

### CODE REVIEW

**Comment by icanhasjonas** [comment]
LGTM

**Comment by dahall** [comment]
Will you merge and then push the updated NuGet package?

**Comment by icanhasjonas** [comment]
It's available here now: https://www.nuget.org/packages/Bmbsqd.Async/0.3.0

**Comment by dahall** [comment]
Thank you for the very quick turn-around!

**Pull request merged**
